on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '24'
          elixir-version: '1.13.2'
          experimental-otp: true
      - run: mix deps.get
      - run: mix test
      - if: github.ref_type == 'tag'
        run: mix hex.build
      - if: github.ref_type == 'tag'
        run: mix hex.publish --yes